http://pad.lv/1717598
https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1717598

=== Begin SRU Template ===
[Impact]
Runcmd cloud-config cannot be run on gce instances due to traceback.

[Test Case]
# Create sample runcmd yaml which reproduces failure
$ cat > runcmd.yaml <<EOF
#cloud-config
runcmd:
  - touch /tmp/cloud-init-works
EOF

# spawn GCE instance Xenial/Zesty with the following user-data
$ gcloud compute instances create xenial-$(date +%y%m%d-%H%M) --image <daily-xenial-image> --image-project ubuntu-os-cloud-devel --metadata-from-file user-data=cfg

$ ssh ubuntu@<gce-instance>
# Grep for Tracebacks in /var/log/cloud-init.log
ubuntu@gce$ grep Traceback /var/log/cloud-init.log

# Update to <series>-proposed
ubunut@gce$ sudo vi /etc/apt/sources.list ... %s/ xenial / xenial-proposed /
ubunut@gce$ sudo apt update
ubunut@gce$ sudo apt install cloud-init
ubunut@gce$ dpkg-query show cloud-init
ubunut@gce$ sudo rm /var/lib/cloud /var/log/cloud*; sudo reboot
# Recheck with proposed run
$ ssh ubuntu@<gce-instance>
ubunut@gce$ grep Traceback /var/log/cloud-init.log


[Regression Potential]
Minimal, This fix is minor and resolves an existing bug preventing runcmd configs from being run at all.


[Other Info]
Upstream commit at
  https://git.launchpad.net/cloud-init/commit/?id=10f067d8

=== End SRU Template ===
