Upstream test at:
https://github.com/canonical/cloud-init/blob/master/tests/integration_tests/test_upgrade.py

Logs from individual before/after runs in gce-sru-20.4.0 subdirectory

==== Xenial ====
================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, inifile: tox.ini
plugins: cov-2.9.0
collected 1 item

tests/integration_tests/test_upgrade.py Detected image: image_id=xenial os=ubuntu release=xenial
Detected image: image_id=xenial os=ubuntu release=xenial
Detected image: image_id=xenial os=ubuntu release=xenial
Detected image: image_id=xenial os=ubuntu release=xenial
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-server-277015
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa
OS_IMAGE=xenial
PLATFORM=gce
RUN_UNSTABLE=False
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-server-277015
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa
OS_IMAGE=xenial
PLATFORM=gce
RUN_UNSTABLE=False
Detected image: image_id=xenial os=ubuntu release=xenial
Detected image: image_id=xenial os=ubuntu release=xenial
Detected image: image_id=xenial os=ubuntu release=xenial
Detected image: image_id=xenial os=ubuntu release=xenial
Launching instance with launch_kwargs:
user_data=#cloud-config
hostname: SRU-worked

image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-1604-xenial-v20201210
wait=False
Launching instance with launch_kwargs:
user_data=#cloud-config
hostname: SRU-worked

image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-1604-xenial-v20201210
wait=False
Launched instance: GceInstance(instance_id=5326178758279714545)
Launched instance: GceInstance(instance_id=5326178758279714545)
Installing proposed image
Installing proposed image
Installed cloud-init version: 20.4-0ubuntu1~16.04.1
Installed cloud-init version: 20.4-0ubuntu1~16.04.1
Instance restarted; waiting for boot
Instance restarted; waiting for boot
Wrote upgrade test logs to /tmp/cloud_init_test_logs/test_upgrade_gce_xenial_before_201211154340.log and /tmp/cloud_init_test_logs/test_upgrade_gce_xenial_after_201211154340.log
Wrote upgrade test logs to /tmp/cloud_init_test_logs/test_upgrade_gce_xenial_before_201211154340.log and /tmp/cloud_init_test_logs/test_upgrade_gce_xenial_after_201211154340.log
.

=========================================================================================== 1 passed in 146.00s (0:02:26) ===========================================================================================

==== Bionic ====

================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, inifile: tox.ini
plugins: cov-2.9.0
collected 1 item

tests/integration_tests/test_upgrade.py Detected image: image_id=bionic os=ubuntu release=bionic
Detected image: image_id=bionic os=ubuntu release=bionic
Detected image: image_id=bionic os=ubuntu release=bionic
Detected image: image_id=bionic os=ubuntu release=bionic
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-server-277015
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa
OS_IMAGE=bionic
PLATFORM=gce
RUN_UNSTABLE=False
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-server-277015
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa
OS_IMAGE=bionic
PLATFORM=gce
RUN_UNSTABLE=False
Detected image: image_id=bionic os=ubuntu release=bionic
Detected image: image_id=bionic os=ubuntu release=bionic
Detected image: image_id=bionic os=ubuntu release=bionic
Detected image: image_id=bionic os=ubuntu release=bionic
Launching instance with launch_kwargs:
user_data=#cloud-config
hostname: SRU-worked

wait=False
image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-1804-bionic-v20201211a
Launching instance with launch_kwargs:
user_data=#cloud-config
hostname: SRU-worked

wait=False
image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-1804-bionic-v20201211a
Launched instance: GceInstance(instance_id=1727796673121244227)
Launched instance: GceInstance(instance_id=1727796673121244227)
Installing proposed image
Installing proposed image
Installed cloud-init version: 20.4-0ubuntu1~18.04.1
Installed cloud-init version: 20.4-0ubuntu1~18.04.1
Instance restarted; waiting for boot
Instance restarted; waiting for boot
Wrote upgrade test logs to /tmp/cloud_init_test_logs/test_upgrade_gce_bionic_before_201211155437.log and /tmp/cloud_init_test_logs/test_upgrade_gce_bionic_after_201211155437.log
Wrote upgrade test logs to /tmp/cloud_init_test_logs/test_upgrade_gce_bionic_before_201211155437.log and /tmp/cloud_init_test_logs/test_upgrade_gce_bionic_after_201211155437.log
.

=========================================================================================== 1 passed in 146.39s (0:02:26) ===========================================================================================

==== Focal ====
================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, inifile: tox.ini
plugins: cov-2.9.0
collected 1 item

tests/integration_tests/test_upgrade.py Detected image: image_id=focal os=ubuntu release=focal
Detected image: image_id=focal os=ubuntu release=focal
Detected image: image_id=focal os=ubuntu release=focal
Detected image: image_id=focal os=ubuntu release=focal
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-server-277015
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa
OS_IMAGE=focal
PLATFORM=gce
RUN_UNSTABLE=False
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-server-277015
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa
OS_IMAGE=focal
PLATFORM=gce
RUN_UNSTABLE=False
Detected image: image_id=focal os=ubuntu release=focal
Detected image: image_id=focal os=ubuntu release=focal
Detected image: image_id=focal os=ubuntu release=focal
Detected image: image_id=focal os=ubuntu release=focal
Launching instance with launch_kwargs:
user_data=#cloud-config
hostname: SRU-worked

wait=False
image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-2004-focal-v20201211
Launching instance with launch_kwargs:
user_data=#cloud-config
hostname: SRU-worked

wait=False
image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-2004-focal-v20201211
Launched instance: GceInstance(instance_id=3221830879877682049)
Launched instance: GceInstance(instance_id=3221830879877682049)
Installing proposed image
Installing proposed image
Installed cloud-init version: 20.4-0ubuntu1~20.04.1
Installed cloud-init version: 20.4-0ubuntu1~20.04.1
Instance restarted; waiting for boot
Instance restarted; waiting for boot
Wrote upgrade test logs to /tmp/cloud_init_test_logs/test_upgrade_gce_focal_before_201211160622.log and /tmp/cloud_init_test_logs/test_upgrade_gce_focal_after_201211160622.log
Wrote upgrade test logs to /tmp/cloud_init_test_logs/test_upgrade_gce_focal_before_201211160622.log and /tmp/cloud_init_test_logs/test_upgrade_gce_focal_after_201211160622.log
.

=========================================================================================== 1 passed in 185.57s (0:03:05) ===========================================================================================

==== Groovy ====
================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, inifile: tox.ini
plugins: cov-2.9.0
collected 1 item

tests/integration_tests/test_upgrade.py Detected image: image_id=groovy os=ubuntu release=groovy
Detected image: image_id=groovy os=ubuntu release=groovy
Detected image: image_id=groovy os=ubuntu release=groovy
Detected image: image_id=groovy os=ubuntu release=groovy
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-server-277015
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa
OS_IMAGE=groovy
PLATFORM=gce
RUN_UNSTABLE=False
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-server-277015
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa
OS_IMAGE=groovy
PLATFORM=gce
RUN_UNSTABLE=False
Detected image: image_id=groovy os=ubuntu release=groovy
Detected image: image_id=groovy os=ubuntu release=groovy
Detected image: image_id=groovy os=ubuntu release=groovy
Detected image: image_id=groovy os=ubuntu release=groovy
Launching instance with launch_kwargs:
user_data=#cloud-config
hostname: SRU-worked

image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-2010-groovy-v20201210
wait=False
Launching instance with launch_kwargs:
user_data=#cloud-config
hostname: SRU-worked

image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-2010-groovy-v20201210
wait=False
Launched instance: GceInstance(instance_id=7135800809689599695)
Launched instance: GceInstance(instance_id=7135800809689599695)
Installing proposed image
Installing proposed image
Installed cloud-init version: 20.4-0ubuntu1~20.10.1
Installed cloud-init version: 20.4-0ubuntu1~20.10.1
Instance restarted; waiting for boot
Instance restarted; waiting for boot
Wrote upgrade test logs to /tmp/cloud_init_test_logs/test_upgrade_gce_groovy_before_201211161750.log and /tmp/cloud_init_test_logs/test_upgrade_gce_groovy_after_201211161750.log
Wrote upgrade test logs to /tmp/cloud_init_test_logs/test_upgrade_gce_groovy_before_201211161750.log and /tmp/cloud_init_test_logs/test_upgrade_gce_groovy_after_201211161750.log
.

=========================================================================================== 1 passed in 172.79s (0:02:52) ===========================================================================================